name: sru validation workflow for snapd package
checklists:
    Sign-Off:
        - name: Approved
          default: false
        - name: Rejected
          default: false
    Autopkgtest tests:
        - name: Bionic - http://people.canonical.com/~ubuntu-archive/proposed-migration/bionic/update_excuses.html#snapd
          default: false
        - name: Focal - http://people.canonical.com/~ubuntu-archive/proposed-migration/focal/update_excuses.html#snapd
          default: false
        - name: Hirsute - https://people.canonical.com/~ubuntu-archive/proposed-migration/hirsute/update_excuses.html#snapd
          default: false
        - name: Impish - https://people.canonical.com/~ubuntu-archive/proposed-migration/impish/update_excuses.html#snapd
          default: false
        - name: Jammy - https://people.canonical.com/~ubuntu-archive/proposed-migration/jammy/update_excuses.html#snapd
          default: false
    Manual checks:
        - name: Review changelog
          default: false
        - name: Verify associated bugs
          default: false
        - name: Run tests described on lp
          default: false
    Automated tests:
        - name: Bionic
          default: false
        - name: Focal
          default: false
        - name: Hirsute
          default: false
        - name: Impish
          default: false
        - name: Jammy
          default: false
    Manual tests:
        - name: Bionic
          default: false
        - name: Focal
          default: false
        - name: Hirsute
          default: false
        - name: Impish
          default: false
        - name: Jammy
          default: false